### ISSUE TITLE
The sessions account I purchased shows the following error after running

### ISSUE THREAD

**Issue by kenxs33** [Cryptonian007/Astra#15]
The sessions account I purchased shows the following error after running
Traceback (most recent call last):
  File "add.py", line 175, in <module>
    c.start(acc[0])
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_
until_complete
    return future.result()
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\auth.py", line 146, in _start
    me = await self.get_me()
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 147, in get_me
    me = (await self(
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 78, in _call
    self.session.process_entities(result)
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\ses
sions\sqlite.py", line 281, in process_entities
    c.executemany(
sqlite3.OperationalError: table entities has 6 columns but 5 values were supplie
d

**Comment by Cryptonian007** [comment]
Try deleting the accounts and adding them again
