### ISSUE TITLE
i keep getting this error after adding second account  and running add.py

### ISSUE THREAD

**Issue by Diogovski** [Cryptonian007/Astra#8]
Traceback (most recent call last):
  File "C:\Users\ribei\Downloads\Astra-main\Astra-main\add.py", line 87, in <module>
    clnt.send_code_request(phn)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\auth.py", line 497, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 56, in _call
    future = sender.send(request, ordered=ordered)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\network\mtprotosender.py", line 172, in send
    state = RequestState(request)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\network\requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\tl\tlobject.py", line 190, in __bytes__
    return self._bytes()
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\tl\functions\auth.py", line 486, in _bytes
    self.serialize_bytes(self.phone_number),
  File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\tl\tlobject.py", line 108, in serialize_bytes
    raise TypeError(
TypeError: bytes or str expected, not <class 'NoneType'>

**Comment by Cryptonian007** [comment]
If you're running in an IDE, switch to a terminal. Or instead, you can close the other scripts running when you're running one, e.g. if you are running `add.py` and `manager.py` is still active, close it

**Comment by Mod786** [comment]
Pls bro give update in astra niw its not working good its only scrape 10-20members pls bro help
